### ISSUE TITLE
SSL connections time out at some point, causing the next request handler to fail with `NIOOpenSSL.OpenSSLError.uncleanShutdown`

### ISSUE THREAD

**Issue by MrMage** [vapor/postgres-kit#137]
I am using this PostgreSQL handler together with fluent and the database connection pool. It appears that Postgres connections using TLS sometimes get closed after long periods of inactivity. The next request handler that fetches such a connection from the connection pool will then fail with an `NIOOpenSSL.OpenSSLError.uncleanShutdown` error.

The connection pool should only use non-closed connections, anyway, so I suspect that this error does not cause the connection to close immediately. Instead, the error is only surfaced when we try to send a Postgres command via the connection and the connection is then closed (I think).

**Are there any options for detecting SSL disconnects right when they occur (and then closing the connection immediately) instead of the next time the connection is used?**

/cc @tanner0101 @FranzBusch

**Comment by tanner0101** [comment]
@MrMage we might be able to check the `channel.isActive` property. (This is what `PostgresNIO` does in Vapor 4) Perhaps [`PostgresConnection.isClosed`](stored: https://github.com/vapor/postgres-kit/blob/1/Sources/PostgreSQL/Connection/PostgreSQLConnection.swift#L15) could be a computed property on `channel.isActive` instead of stored as it is currently. 

Are you able to re-create this issue locally or just in production? If you can re-create locally, then we could give this change a shot and see if it helps without breaking other stuff.

**Comment by MrMage** [comment]
> Are you able to re-create this issue locally or just in production? If you can re-create locally, then we could give this change a shot and see if it helps without breaking other stuff.

I haven't tried, but it seems to occur only after long periods (a few hours?) of not using the connection. Also, reducing the KEEPALIVE delay in my Postgres config seems to avoid the issue for now, but I guess this should still be covered somehow.

**Comment by tanner0101** [comment]
This should no longer be an issue in version 2 of this package now that `isClosed` is computed based on `channel.isActive`.
