### ISSUE TITLE
Keep getting "No available connections on this event loop, creating a new one"

### ISSUE THREAD

**Issue by MoridinBG** [vapor/postgres-kit#196]
I keep getting `No available connections on this event loop, creating a new one` when making queries. I have tried both to create a new database from pool.database(logger:) before each query and to have a common database for all queries.
It's especially bad when I have multiple flatMap chained queries as a connection needs to be done for each one.
I tried increasing the `maxConnectionsPerEventLoop` for the EventLoopGroupConnectionPool, but didn't make a difference.

How do I reuse connections?

I am using postgres-kit standalone from Fluent.

**Comment by 0xTim** [comment]
Do you see this forever? You'll always see this when it first starts running. This is because when the app first starts up, there are no active connections to the DB. So when you request one, it checks the pool and then creates one if there are none available and it's below `maxConnectionsPerEventLoop`. When you chain the queries, it will create as many connections as possible to make it efficient IIRC. Connections are kept open once they've been made to enable additional queries to be performed quicker. Once all the available event loops have created as many connections as they're allowed, then you shouldn't see this message.

The actual message isn't an error, it's just a debug log. At least this is all my understanding of how the connection pool works

**Comment by MoridinBG** [comment]
I think I understand what is going on. I am very new to NIO, event loops and event loop groups.
When creating a database straight from the `EventLoopGroupConnectionPool` each postgres command is sent over a different event loop and as a result, different connection.
So ideally, query chains should use a database reference with a single event loop connection pool.
